#ifndef CFG_H
#define CFG_H

#define CFG_PROFILE_PROFILEID 0U
#define CFG_PROFILE_STARTFREQCONST 1435388860U
#define CFG_PROFILE_IDLETIMECONST 1000U
#define CFG_PROFILE_ADCSTARTTIMECONST 700U
#define CFG_PROFILE_RAMPENDTIME 2081U
#define CFG_PROFILE_FREQSLOPECONST 932U
#define CFG_PROFILE_NUMADCSAMPLES 256U
#define CFG_PROFILE_DIGOUTSAMPLERATE 30000U
#define CFG_PROFILE_RXGAIN 164U
#define CFG_OPEN_CHCONF_RXEN_BMASK 0b1111

#define CFG_ADCBUF_PINGPONG_THRESHOLD 1

#define NUM_RX_ANTENNAS ( ((CFG_OPEN_CHCONF_RXEN_BMASK & 0b0001) > 0 ? 1 : 0) + ((CFG_OPEN_CHCONF_RXEN_BMASK & 0b0010) > 0 ? 1 : 0) + \
                        ((CFG_OPEN_CHCONF_RXEN_BMASK & 0b0100) > 0 ? 1 : 0) + ((CFG_OPEN_CHCONF_RXEN_BMASK & 0b1000) > 0 ? 1 : 0) )

// TODO: get this from a txen bitmask too
#define NUM_TX_ANTENNAS 4

#define CHIRPS_PER_FRAME    128

// Doppler chirps will always be the total chirps in a frame / enabled rx
#define NUM_DOPPLER_CHIRPS (CHIRPS_PER_FRAME / NUM_RX_ANTENNAS)
#define NUM_RANGEBINS       (CFG_PROFILE_NUMADCSAMPLES / 2)
#define CPLX_SAMPLE_SIZE (sizeof(int16_t) * 2)

#define SAMPLE_SIZE         (sizeof(uint16_t))
#define CHIRP_DATASIZE      (NUM_RX_ANTENNAS * CFG_PROFILE_NUMADCSAMPLES * SAMPLE_SIZE)
#define FRAME_DATASIZE      (NUM_RANGEBINS * NUM_RX_ANTENNAS * NUM_TX_ANTENNAS * NUM_DOPPLER_CHIRPS * sizeof(uint32_t))
#define UDP_BYTES_PER_PKT   1024
#define UDP_PKT_CNT         (FRAME_DATASIZE / UDP_BYTES_PER_PKT)





#endif
